## Dasar Sistem Cerdas: Assignment 2:
#### Name: Armand Faris A Surbakti
#### NRP: 5023201051


##### Design  McPit ANN Model for XOR function with 8 input variables. Realize computer program to simulate the model in realizing the logic function.
##### Write your report of method of design to get your solution, realization of computer program to simulate the McPit ANN model of XOR 8 inputs.
<img src="8 input model.png" alt="8 input example" width=500 height=250>




In [2]:
#Here is a program for 2nd DSC Assignment, McPit ANN Model for XOR Function

#import  necessary libraries
import numpy as np
import pandas as pd

#Next we are going to read the csv data for 8 inputs
dataset = pd.read_csv('xor_8input.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

##### This is the csv data for the 8 input xor model. X here will be denoted as the input, and y will be the output layer. 
##### We use pandas library to split the data in x and y
##### We can follow this notation as an example:
<img src="x_y input model.png" width=500 height=250>

##### After this we encode the data here, as we see here, X is the input data and as a boolean data type (containing TRUE or FALSE)
##### y as the output layer is also a boolean data type (containing TRUE or FALSE)
##### the iloc function in pandas is used to retrieve data and split into columns and rows



In [3]:
#initiate the x input layer
x

[[False False False ... False False False]
 [False False False ... False False  True]
 [False False False ... False  True False]
 ...
 [ True  True  True ...  True False  True]
 [ True  True  True ...  True  True False]
 [ True  True  True ...  True  True  True]]


In [4]:
#inititate the y output layer
y

array([False,  True,  True, False,  True, False, False,  True,  True,
       False, False,  True, False,  True,  True, False,  True, False,
       False,  True, False,  True,  True, False, False,  True,  True,
       False,  True, False, False,  True,  True, False, False,  True,
       False,  True,  True, False, False,  True,  True, False,  True,
       False, False,  True, False,  True,  True, False,  True, False,
       False,  True,  True, False, False,  True, False,  True,  True,
       False,  True, False, False,  True, False,  True,  True, False,
       False,  True,  True, False,  True, False, False,  True, False,
        True,  True, False,  True, False, False,  True,  True, False,
       False,  True, False,  True,  True, False, False,  True,  True,
       False,  True, False, False,  True,  True, False, False,  True,
       False,  True,  True, False,  True, False, False,  True, False,
        True,  True, False, False,  True,  True, False,  True, False,
       False,  True,

##### To Simplify Visualization, we can convert the TRUE/FALSE data into just binary data (using 0s and 1s)
##### This is also known as data encoding
##### We can use the numpy multiply function here. numpy.multiply() function is used when we want to compute the multiplication of two arrays.



In [5]:
encode_x = np.multiply(x,1)
#convert encode_x into 0 and 1s arrays
encode_x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1]])

#### Do the same process as y output layer


In [6]:
encoded_y = np.multiply(y,1)
#convert encode_y into 0 and 1s arrays
encoded_y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0])

##### After this encoding both x and y, we have to determine the total amount of inputs, rows, and TRUE outputs from the 8 inputs dataset
##### We can use len to determine the total amount of input and sum of TRUE outputs in the y layer
##### The purpose of this to find out about the Hidden layer. The Hidden layer is the layer that is inbetween the input and output of the algorithm
##### the function applies weights to the inputs and directs the inputs through an activation function (in this case, y layer)

In [7]:
#using len() to find out total amout of inputs
n_input = len(x[0])
#finding out the rows 
row = len(y)
#sum of true in the output layer
sum_true = y.sum()

##### Before we move forward, we need to determine TLU
##### TLU is the threshold logic unit, it is a simple artificial neuron (also called the M-P Neuron) whose output it its thresholded total net input
<img src="tlu_model.png" alt="tlu model" height = 200, width = 400>

In [8]:
#Make a tlu function for this input layer
#convert it into an array using np.array()
tlu = np.array([])
for j in range(row):
    if y[j] == 1:
      #if output layer = TRUE, append exhibitory inputs
      tlu = np.append(tlu, x[j].sum())

#### Finding the Weights
##### Weight is the parameter within a neural network that transforms input data within the network's hidden layers. 
##### as an input enters the node, it gets multiplied by a weight value.
<img src="weight_example.png" alt="weight">

##### The weight of the first layer is done by converting the 0 inputs (false inputs) into -1
##### We can follow this equation here, w=-c:
<img src="weight_equation.png"  alt="w">

In [9]:
#convert weight layer into an array
weight_layer1 = np.array([])
for i in np.where(y == 1)[0]:
        j = x[i]
        cont = np.where(j == 0, -1, j)
        #the numpy concatenate function is used to join 2 arrays into 1
        weight_layer1 = np.concatenate((weight_layer1, cont))
        #after computing the weights, we can use the reshape() to reshape the array
weight_layer1 = weight_layer1.reshape((sum_true, n_input))

weight_layer1

array([[-1., -1., -1., ..., -1., -1.,  1.],
       [-1., -1., -1., ..., -1.,  1., -1.],
       [-1., -1., -1., ...,  1., -1., -1.],
       ...,
       [ 1.,  1.,  1., ..., -1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1., -1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1., -1.]])

##### After computing the weights, we now move on to create and program the 1st layer
##### We create variables specifically for our x input layer, and then move it to the threshold
##### TLU will determine the output, which will move on to the 2nd layer
##### if the inputs of layer 1 exceeds or level to threshold, then output 1
##### if not, output will be 0 (in this case, an inhibitory neuron)

In [10]:
#Set Variables
#Remember that the input layers are the sum of all TRUE/0 variables
in_layer1 = np.zeros(sum_true)
#create an output layer for 1st layer
out_layer1 = np.zeros(sum_true)
for j in range(sum_true):
    for k in range(n_input):
        in_layer1[j] += weight_layer1[j,k] * x[1,k]
    #if the inputs of layer 1 exceeds or level to threshold, then output 1
    #if not, output 0 (in this case, an inhibitory neuron)
    if in_layer1[j] >= tlu[j]:
        out_layer1 [j] = 1
    else:
        out_layer1 [j] = 0
out_layer1


array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### Creating the 2nd Layer:
##### After creating and outputting the 1st layer, we move on the 2nd layer by doing the same process
##### In this case the inputs here are the outputs of the 1st layer. Move it through threshold, and apply the same logic.


In [11]:
#create second layer variables
tlu_layer2 = 1
weight_layer2 = np.ones(sum_true)
in_layer2 = 0
out_layer2 = 0

#Initiate second layer
for i in range(sum_true):
   in_layer2 += weight_layer2[i] * out_layer1[i]
#Apply TLU Logic
if in_layer2 >= tlu_layer2:
    out_layer2 = 1
else:
    out_layer2 = 0
    
out_layer2

1

##### Output Layer = 1 means that the TLU and threshold worked.
##### Next we will combine both layers (layer 1 and 2) into a single function
##### The purpose of combining into 1 function is so that the model can be trained to output 1 set of a single truth_table
##### Here, we use the same code from layers 1 and 2


In [60]:
def combined_layer_functon(input):
    tlu = np.array([])
    for j in range(row):
       if y[j] == 1:
          tlu = np.append(tlu, x[j].sum())
    weight_layer1 = np.array([])
    for i in np.where(y == 1)[0]:
        j = x[i]
        cont = np.where(j == 0, -1, j)
        weight_layer1 = np.concatenate((weight_layer1, cont))
    weight_layer1 = weight_layer1.reshape((sum_true, n_input))    
    
    #set variables for 1st layer  
    in_layer1 = np.zeros(sum_true)
    #create an output layer for 1st layer
    out_layer1 = np.zeros(sum_true)
    for j in range(sum_true):
        for k in range(n_input):
            in_layer1[j] += weight_layer1[j,k] * input[k]
    #if the inputs of layer 1 exceeds or level to threshold, then output 1
    #if not, output 0 (in this case, an inhibitory neuron)
        if in_layer1[j] >= tlu[j]:
           out_layer1 [j] = 1
        else:
           out_layer1 [j] = 0
           
    #Continute to the 2nd layer
    tlu_layer2 = 1
    weight_layer2 = np.ones(sum_true)
    in_layer2 = 0
    out_layer2 = 0
    #Initiate second layer
    for i in range(sum_true):
        in_layer2 += weight_layer2[i] * out_layer1[i]
    #Apply TLU Logic
    if in_layer2 >= tlu_layer2:
        out_layer2 = 1
    else:
        out_layer2 = 0
    #return output of 2nd layer 
    return out_layer2
    

##### Calculation for Input Set for Truth Table with for loop iteration to train the model
##### This is the calculation process for every x input, which will be stored as "y_function_output" variable


In [61]:
#Calculation
y_function_output = np.zeros(row)
for i in range(row):
    #apply the combined function into the x input
    y_function_output[i] = combined_layer_functon(x[i])

y_function_output

array([0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1.,
       0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
       0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 1., 1., 0.

##### Using Confusion Matrix to evaluate model calculation
##### The Confusion Matrix is a specific table layout that allows visualization of the performance of an algorithm.
##### In this case, it has 4 variable combination which is False Positive, False Negative, True Positive, True Negative
##### False Neg and False Pos is an outcome where the model incorrectly predicts the negative class. While true positive is the outcome where the model correctly predicts the outcome.
<img src="confusion matrix model.png" alt="confused_matrix">


In [62]:
#We create a 2x2 array since the confusion matrix is a 2x2 table.
confusion_matrix = np.zeros((2,2))
for i in range(row):
    #False Positive
    if (y_function_output[i] == y[i]) and (y_function_output[i] == 0): 
        confusion_matrix[0,0] += 1
    #False Negative
    elif (y_function_output[i] != y[i]) and (y_function_output[i] == 0): 
        confusion_matrix[0,1] += 1
    #True Negative
    elif (y_function_output[i] != y[i]) and (y_function_output[i] == 1):
        confusion_matrix[1,0] += 1
    #True Positive
    elif (y_function_output[i] == y[i]) and (y_function_output[i] == 1):
        confusion_matrix[1,1] += 1

confusion_matrix = pd.DataFrame(confusion_matrix, dtype=int)

print('Confusion Matrix : ')
confusion_matrix

Confusion Matrix : 


0    1
0  128    0
1    0  128

##### After Creating the Confusion Matrix, we can now evaluate the accuracy 
##### We can use this formula to calculate our Model's Accuracy
<img src ="model_accuracy_equation.png" alt="eq">

##### Based on the output of the confusion matrix, we can code it like this:


In [63]:
#evaluation model accuracy
false_negative = confusion_matrix.iloc[0,1]
false_positive = confusion_matrix.iloc[0,0]
true_negative =  confusion_matrix.iloc[1,0]
true_positive = confusion_matrix.iloc[1,1]
model_accuracy =  ((false_positive + true_positive) / (false_positive + true_positive + false_negative + true_negative))*100
print("model_accuracy: {} %".format(model_accuracy))


model_accuracy: 100.0 %
